/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author asus
 */
public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnmail = new javax.swing.JButton();
        btnsms = new javax.swing.JButton();
        btnattach = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        txtopno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextArea();
        lblname = new javax.swing.JLabel();
        btnappoinment = new javax.swing.JButton();
        lblname2 = new javax.swing.JLabel();
        btnmedicine = new javax.swing.JButton();
        lblname3 = new javax.swing.JLabel();
        btnpatient = new javax.swing.JButton();
        lblname4 = new javax.swing.JLabel();
        btnpatient1 = new javax.swing.JButton();
        lblname5 = new javax.swing.JLabel();
        btnbookre = new javax.swing.JButton();
        btnmedicine1 = new javax.swing.JButton();
        lblname6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbldate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnsave.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_3floppy_unmount_18268 (1).png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave);
        btnsave.setBounds(70, 120, 90, 30);

        btnsearch.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_search_322497.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch);
        btnsearch.setBounds(480, 120, 110, 30);

        btncancel.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_cancel_326554.png"))); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        getContentPane().add(btncancel);
        btncancel.setBounds(160, 120, 110, 30);

        btnedit.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_edit2_1167984.png"))); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        getContentPane().add(btnedit);
        btnedit.setBounds(270, 120, 100, 30);

        btndelete.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_ic_delete_48px_352303.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete);
        btndelete.setBounds(380, 120, 100, 30);

        btnnew.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_new10_216291.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        getContentPane().add(btnnew);
        btnnew.setBounds(590, 120, 110, 30);

        btnmail.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_81_171440.png"))); // NOI18N
        btnmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmailActionPerformed(evt);
            }
        });
        getContentPane().add(btnmail);
        btnmail.setBounds(760, 120, 100, 30);

        btnsms.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnsms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/Mobile-Sms-icon.png"))); // NOI18N
        btnsms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsmsActionPerformed(evt);
            }
        });
        getContentPane().add(btnsms);
        btnsms.setBounds(670, 120, 90, 30);

        btnattach.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnattach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/Editing-Attach-icon.png"))); // NOI18N
        btnattach.setText("Attach");
        btnattach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnattachActionPerformed(evt);
            }
        });
        getContentPane().add(btnattach);
        btnattach.setBounds(40, 170, 110, 30);

        combo.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        getContentPane().add(combo);
        combo.setBounds(170, 170, 190, 30);

        txtopno.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        txtopno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtopnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtopno);
        txtopno.setBounds(370, 180, 240, 30);

        txtaddress.setColumns(20);
        txtaddress.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        txtaddress.setRows(5);
        jScrollPane1.setViewportView(txtaddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 170, 240, 60);

        lblname.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 0, 0));
        lblname.setText("Enter Name");
        getContentPane().add(lblname);
        lblname.setBounds(40, 220, 170, 30);

        btnappoinment.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnappoinment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_app_type_shop_512px_GREY_287498.png"))); // NOI18N
        btnappoinment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappoinmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnappoinment);
        btnappoinment.setBounds(20, 280, 160, 130);

        lblname2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblname2.setForeground(new java.awt.Color(0, 102, 102));
        lblname2.setText("Purchase");
        getContentPane().add(lblname2);
        lblname2.setBounds(50, 410, 170, 30);

        btnmedicine.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnmedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_shopping_bag_289613.png"))); // NOI18N
        btnmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicineActionPerformed(evt);
            }
        });
        getContentPane().add(btnmedicine);
        btnmedicine.setBounds(190, 280, 160, 130);

        lblname3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblname3.setForeground(new java.awt.Color(0, 102, 102));
        lblname3.setText("Stock");
        getContentPane().add(lblname3);
        lblname3.setBounds(230, 410, 170, 30);

        btnpatient.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnpatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/Patients-icon.png"))); // NOI18N
        btnpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientActionPerformed(evt);
            }
        });
        getContentPane().add(btnpatient);
        btnpatient.setBounds(360, 280, 160, 130);

        lblname4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblname4.setForeground(new java.awt.Color(0, 102, 102));
        lblname4.setText("Manage Patients");
        getContentPane().add(lblname4);
        lblname4.setBounds(370, 410, 170, 30);

        btnpatient1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnpatient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_order-history_49596.png"))); // NOI18N
        btnpatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatient1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnpatient1);
        btnpatient1.setBounds(530, 280, 160, 130);

        lblname5.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblname5.setForeground(new java.awt.Color(0, 102, 102));
        lblname5.setText("Reports");
        getContentPane().add(lblname5);
        lblname5.setBounds(580, 410, 170, 30);

        btnbookre.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnbookre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/if_adept_update_7685.png"))); // NOI18N
        btnbookre.setText("Renew and Book");
        btnbookre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookreActionPerformed(evt);
            }
        });
        getContentPane().add(btnbookre);
        btnbookre.setBounds(250, 210, 161, 30);

        btnmedicine1.setFont(new java.awt.Font("Garamond", 1, 24)); // NOI18N
        btnmedicine1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/medicine.png"))); // NOI18N
        btnmedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmedicine1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnmedicine1);
        btnmedicine1.setBounds(710, 290, 160, 130);

        lblname6.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblname6.setForeground(new java.awt.Color(0, 102, 102));
        lblname6.setText("Medicines");
        getContentPane().add(lblname6);
        lblname6.setBounds(720, 430, 170, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Plantagenet Cherokee", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("ACTYMED | DESIGNATIONS");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(140, 20, 590, 50);

        lbldate.setFont(new java.awt.Font("PMingLiU", 1, 14)); // NOI18N
        lbldate.setText("date");
        jPanel6.add(lbldate);
        lbldate.setBounds(790, 50, 200, 20);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1240, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        //driver loading.

    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmailActionPerformed

    private void btnsmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsmsActionPerformed

    private void btnattachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnattachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnattachActionPerformed

    private void txtopnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtopnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtopnoActionPerformed

    private void btnappoinmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappoinmentActionPerformed

    }//GEN-LAST:event_btnappoinmentActionPerformed

    private void btnmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmedicineActionPerformed

    private void btnpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpatientActionPerformed

    private void btnpatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpatient1ActionPerformed

    private void btnbookreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbookreActionPerformed

    private void btnmedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmedicine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmedicine1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnappoinment;
    private javax.swing.JButton btnattach;
    private javax.swing.JButton btnbookre;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnmail;
    private javax.swing.JButton btnmedicine;
    private javax.swing.JButton btnmedicine1;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnpatient;
    private javax.swing.JButton btnpatient1;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsms;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname3;
    private javax.swing.JLabel lblname4;
    private javax.swing.JLabel lblname5;
    private javax.swing.JLabel lblname6;
    private javax.swing.JTextArea txtaddress;
    private javax.swing.JTextField txtopno;
    // End of variables declaration//GEN-END:variables
}
