/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import connection.MysqlConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class ViewPatient extends javax.swing.JFrame {

    /**
     * Creates new form ViewPatient
     */
     PreparedStatement pst=null;
    ResultSet rs=null; 
    public void dbconnection() throws SQLException
     {
     MysqlConnection db = new MysqlConnection();
     Statement st = db.connection.createStatement();     
     }
    public ViewPatient() {
        initComponents();
        filldoctor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void filldoctor()
    {
        try
        {
            MysqlConnection db = new MysqlConnection();
            pst=db.connection.prepareStatement("SELECT * from hms_employeeregistration where designation_id=2" );
            rs=pst.executeQuery();
            while(rs.next())
            {
                combodr.addItem(rs.getString("emp_name"));
             
            }
            
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"error ");
   
        }
    }
    public void getempid()
    {
        try
        {
            MysqlConnection db = new MysqlConnection();
            pst=db.connection.prepareStatement("SELECT emp_id from hms_employeeregistration where emp_name='"+combodr.getSelectedItem()+"'" );
            rs=pst.executeQuery();
            while(rs.next())
            {
                int id=rs.getInt("emp_id");
                jTextField1.setText(""+id);
             
            }
            
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"error in getting data for sate");
   
        }
    }
     public void ViewPatients()
    {
        try
        {
            MysqlConnection db = new MysqlConnection();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             String date = sdf.format(jDateChooser1.getDate());
            System.out.println(date);
          //  pst=db.connection.prepareStatement("select o.op_id,o.op_name,o.op_gender,o.op_address,o.place,o.op_phone,o.op_email,b.booking_date from hms_opregistration o ,hms_bookingop b where b.op_id=o.op_id and b.booking_date='2018-07-17'" );
          // pst=db.connection.prepareStatement("select o.op_id,o.op_name,o.op_gender,o.op_address,o.place,o.op_phone,o.op_email,e.* from hms_opregistration o ,hms_bookingop b,hms_employeeregistration e where b.emp_id=e.emp_id and  b.op_id=o.op_id and b.emp_id='"+jTextField1.getText()+"' and b.booking_date='"+date+"'"); 
             pst=db.connection.prepareStatement("select o.op_id,o.op_name,o.op_gender,o.op_address,o.place,o.op_phone,o.op_email,b.booking_date from hms_bookingop b,hms_opregistration o,hms_employeeregistration e where b.booking_date='"+date+"' and  b.emp_id='"+jTextField1.getText()+"'  and e.emp_id=b.emp_id and o.op_id=b.op_id "); 
           rs=pst.executeQuery();
             System.out.println(pst);
           try
           {
            while(rs.next())
            {
                //System.out.println(rs.getString("op_email"));
                
               // jTable2.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
             
            }
           }
           catch(Exception ex )
           {
               System.out.println(ex);
           }
            
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(null,"error "+e); 
        }
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        combodr = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 1500));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(81, 92, 147));
        jPanel1.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 255));
        jLabel14.setText("ACTYMED Centre for Orthopaedics & Sports Medicine  Run by: Sports & Games Welfare Association-Kerala");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 20, 980, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1440, 70);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("PMingLiU", 0, 14)); // NOI18N
        jLabel11.setText("Date");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 70, 120, 30);

        jLabel3.setFont(new java.awt.Font("PMingLiU", 0, 14)); // NOI18N
        jLabel3.setText("Doctor");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 130, 120, 30);

        btnsearch.setFont(new java.awt.Font("Garamond", 1, 14)); // NOI18N
        btnsearch.setText("Ok");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnsearch);
        btnsearch.setBounds(480, 130, 100, 30);

        combodr.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        combodr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        combodr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodrActionPerformed(evt);
            }
        });
        jPanel2.add(combodr);
        combodr.setBounds(190, 130, 240, 30);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(200, 170, 140, 40);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(190, 70, 230, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 1430, 270);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 0, 920, 402);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 380, 1420, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
      ViewPatients();
    }//GEN-LAST:event_btnsearchActionPerformed

    private void combodrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodrActionPerformed
     getempid();
    }//GEN-LAST:event_combodrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> combodr;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
